language: generic
sudo: require
services: 
  - docker

before_install:
  - docker build -t aronp/docker-example -f Dockerfile.dev .

script:
  - docker run -e CI=true aronp/docker-example npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-612258774112"
  bucket_path: "docker-react"
  on: 
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
