language: generic
sudo: require
services: 
  - docker

before_install:
  - docker build -t aronp/docker-example -f Dockerfile.dev .

script:
  - docker run -e CI=true aronp/docker-example npm run test -- --coverage